title: User

columns:
  left:
    width: 1/2
    fields:
      street:
        label: Straße
        type: text
      zip:
        label: Postleitzahl
        type: text
        width: 1/4
      city:
        label: Stadt
        type: text
        width: 3/4
      country:
        label: Land
        type: text

  right:
    width: 1/2
    fields:
      website:
        label: Website
        type: url
      twitter:
        label: Twitter
        type: text
        icon: twitter
        placeholder: @username
      instagram:
        label: Instagram
        type: text
        icon: instagram
        placeholder: username